
--  Generated by a script from an "avr tools device file" (atdf)

package SAM.Interrupt_Names is

   Number_Of_Interrupts : constant := 30;

   ac_interrupt                   : constant := 24;
   ac1_interrupt                  : constant := 28;
   adc_interrupt                  : constant := 23;
   dac_interrupt                  : constant := 25;
   dmac_interrupt                 : constant := 6;
   eic_interrupt                  : constant := 4;
   evsys_interrupt                : constant := 8;
   nvmctrl_interrupt              : constant := 5;
   pm_interrupt                   : constant := 0;
   rtc_interrupt                  : constant := 3;
   sercom0_interrupt              : constant := 9;
   sercom1_interrupt              : constant := 10;
   sercom2_interrupt              : constant := 11;
   sercom3_interrupt              : constant := 12;
   sercom4_interrupt              : constant := 13;
   sercom5_interrupt              : constant := 14;
   sysctrl_interrupt              : constant := 1;
   tc3_interrupt                  : constant := 18;
   tc4_interrupt                  : constant := 19;
   tc5_interrupt                  : constant := 20;
   tc6_interrupt                  : constant := 21;
   tc7_interrupt                  : constant := 22;
   tcc0_interrupt                 : constant := 15;
   tcc1_interrupt                 : constant := 16;
   tcc2_interrupt                 : constant := 17;
   tcc3_interrupt                 : constant := 29;
   wdt_interrupt                  : constant := 2;
end SAM.Interrupt_Names;
