description = "Drivers and HAL for the SAMD51 micro-controller family"
name = "samd51_hal"
version = "0.3.0"
licenses = "BSD-3-Clause"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]
project-files = [
    "ATSAMD21E15A.gpr",
    "ATSAMD21E15B.gpr",
    "ATSAMD21E15BU.gpr",
    "ATSAMD21E15CU.gpr",
    "ATSAMD21E15L.gpr",
    "ATSAMD21E16A.gpr",
    "ATSAMD21E16B.gpr",
    "ATSAMD21E16BU.gpr",
    "ATSAMD21E16CU.gpr",
    "ATSAMD21E16L.gpr",
    "ATSAMD21E17A.gpr",
    "ATSAMD21E17D.gpr",
    "ATSAMD21E17DU.gpr",
    "ATSAMD21E17L.gpr",
    "ATSAMD21E18A.gpr",
    "ATSAMD21G15A.gpr",
    "ATSAMD21G15B.gpr",
    "ATSAMD21G15L.gpr",
    "ATSAMD21G16A.gpr",
    "ATSAMD21G16B.gpr",
    "ATSAMD21G16L.gpr",
    "ATSAMD21G17A.gpr",
    "ATSAMD21G17AU.gpr",
    "ATSAMD21G17D.gpr",
    "ATSAMD21G17L.gpr",
    "ATSAMD21G18A.gpr",
    "ATSAMD21G18AU.gpr",
    "ATSAMD21J15A.gpr",
    "ATSAMD21J15B.gpr",
    "ATSAMD21J16A.gpr",
    "ATSAMD21J16B.gpr",
    "ATSAMD21J17A.gpr",
    "ATSAMD21J17D.gpr",
    "ATSAMD21J18A.gpr",

    "ATSAMD51G18A.gpr",
    "ATSAMD51G19A.gpr",
    "ATSAMD51J18A.gpr",
    "ATSAMD51J19A.gpr",
    "ATSAMD51J20A.gpr",
    "ATSAMD51N19A.gpr",
    "ATSAMD51N20A.gpr",
    "ATSAMD51P19A.gpr",
    "ATSAMD51P20A.gpr",
]
tags = ["embedded", "nostd", "atsamd21", "atsamd51", "microchip", "atmel", "drivers"]

auto-gpr-with=false # User has to select only one project file

[configuration.values]
atomic.Backend = "armv6m"
cortex_m.core = "m0p"

[[depends-on]]
cortex_m = "~0.5"
hal = "~0.3"
usb_embedded = "~0.3"
gnat_arm_elf = "^12.2"
